workflows:
  my-workflow:
    publishing:
      app_store_connect:
        api_key: LionMasterChef
        #api_key: 6f0245cb7d2344859eac49a269cb2f9e
        key_id: K8LHCHLN54
        issuer_id: 69a6de94-01d2-47e3-e053-5b8c7c11a4d1
        submit_to_testflight: true
        beta_groups:
          - Beta Testers

ios-workflow:
    name: iOS Workflow 
    # ....
    environment:
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.lion.ht
 scripts:
    # ... your dependencies installation
    
    - name: Set up code signing settings on Xcode project
      script: xcode-project use-profiles
    
    # ... your build commands

ios-native:
  environment:
    vars:
      BUNDLE_ID: "com.lion.ht"
      XCODE_WORKSPACE: "Unity-iPhone.xcworkspace" # <-- Name of your Xcode workspace
      XCODE_SCHEME: "Unity-iPhone" # <-- Name of your Xcode scheme
scripts:
  # ...
  - name: Build ipa for distribution
    script: | 
      xcode-project build-ipa \
        --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
        --scheme "$XCODE_SCHEME"
artifacts:
  - build/ios/ipa/*.ipa
  - /tmp/xcodebuild_logs/*.log
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
  - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Hedge Technologies for Information Technology LLC
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.lion.ht"
      vars:
        BUNDLE_ID: "com.lion.ht"
        XCODE_WORKSPACE: "Unity-iPhone.xcworkspace" # <-- Put the name of your Xcode workspace here
        XCODE_SCHEME: "Unity-iPhone" # <-- Put the name of your Xcode scheme here
        APP_ID: 6448666144
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: | 
          pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: | 
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - akram84@me.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - Hedge Team

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: true